# Generated by Django 2.2.4 on 2019-09-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MakingSearch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='user_search',
            field=models.CharField(max_length=50),
        ),
    ]
