# Generated by Django 2.2.4 on 2019-09-01 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MakingSearch', '0003_search_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search',
            old_name='data',
            new_name='date',
        ),
    ]
